apiVersion: apps/v1
kind: Deployment
metadata:
  name: 1001225655-deployment
  labels:
    app: revt-1001225655
spec:
  replicas: 2
  selector:
    matchLabels:
      app: revt-1001225655
  template:
    metadata:
      labels:
        app: revt-1001225655
    spec:
      containers:
      - name: mi-contenedor
        image: 047719650114.dkr.ecr.us-east-1.amazonaws.com/j1128282732:latest
        ports:
        - containerPort: 5000
